import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { runPreflight } from '../../scripts/preflight-production.mjs';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'gamestudio-preflight-fixtures-'));
const base={NODE_ENV:'production',GAMESTUDIO_MODE:'production',GAMESTUDIO_DEPLOYMENT:'production',GAMESTUDIO_DOMAIN:'studio.example.com',ACME_EMAIL:'operator@example.com',GAMESTUDIO_PUBLIC_URL:'https://studio.example.com',APP_BASE_URL:'https://studio.example.com',GAMESTUDIO_HOST:'0.0.0.0',GAMESTUDIO_PROXY_HOPS:'1',GAMESTUDIO_DATA_DIR:path.join(directory,'data'),GAMESTUDIO_SESSION_SECRET:crypto.randomBytes(32).toString('hex'),GOOGLE_CLIENT_ID:'123456789-fixture.apps.googleusercontent.com',GOOGLE_CLIENT_SECRET:'GOCSPX-'+crypto.randomBytes(24).toString('hex'),STRIPE_SECRET_KEY:'sk_live_'+crypto.randomBytes(24).toString('hex'),STRIPE_WEBHOOK_SECRET:'whsec_'+crypto.randomBytes(24).toString('hex'),STRIPE_PRICE_PRO_MONTHLY:'price_fixture123'};
const quiet=()=>{throw Error('A config-only test must never invoke the CLI');};

test('configuration validation accepts complete syntactic setup without CLI, SMS or payment requests',async()=>{const r=await runPreflight({env:base,configOnly:true,execute:quiet});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.ok(r.warnings.some(x=>x.includes('no credential verification')));assert.ok(!JSON.stringify(r).includes(base.GOOGLE_CLIENT_SECRET));assert.ok(!JSON.stringify(r).includes(base.STRIPE_SECRET_KEY));});
test('wrong production mode, origin, proxy topology, low entropy secret and incomplete provider fields fail closed',async()=>{for(const patch of [{GAMESTUDIO_MODE:'local'},{GAMESTUDIO_PUBLIC_URL:'http://studio.example.com'},{APP_BASE_URL:'https://other.example.com'},{GAMESTUDIO_DOMAIN:'other.example.com'},{GAMESTUDIO_PROXY_HOPS:'0'},{GAMESTUDIO_SESSION_SECRET:'a'.repeat(40)},{GOOGLE_CLIENT_SECRET:''},{STRIPE_WEBHOOK_SECRET:''},{STRIPE_PRICE_PRO_MONTHLY:''},{OPENAI_API_KEY:'replace-key'}]){const r=await runPreflight({env:{...base,...patch},configOnly:true,execute:quiet});assert.equal(r.ok,false,JSON.stringify(patch));}});
test('production rejects test-mode money while an explicit staging environment permits its provider setup',async()=>{const keys={...base,STRIPE_SECRET_KEY:'sk_test_'+crypto.randomBytes(24).toString('hex')};assert.equal((await runPreflight({env:keys,configOnly:true})).ok,false);assert.equal((await runPreflight({env:{...keys,GAMESTUDIO_DEPLOYMENT:'staging'},configOnly:true})).ok,true);});
test('Alipay requires actual RSA key types and exact decimal positive amounts, accepting multiline or literal escaped PEM',async()=>{const rsa=crypto.generateKeyPairSync('rsa',{modulusLength:2048}), ec=crypto.generateKeyPairSync('ec',{namedCurve:'P-256'});const env={...base,STRIPE_SECRET_KEY:'',STRIPE_WEBHOOK_SECRET:'',STRIPE_PRICE_PRO_MONTHLY:'',ALIPAY_APP_ID:'2026000000000001',ALIPAY_SELLER_ID:'2088000000000001',ALIPAY_PRIVATE_KEY:rsa.privateKey.export({format:'pem',type:'pkcs8'}),ALIPAY_PUBLIC_KEY:rsa.publicKey.export({format:'pem',type:'spki'}),ALIPAY_PRO_MONTHLY_AMOUNT:'129.00'};assert.equal((await runPreflight({env,configOnly:true})).ok,true);assert.equal((await runPreflight({env:{...env,ALIPAY_PRIVATE_KEY:env.ALIPAY_PRIVATE_KEY.replaceAll('\n','\\n'),ALIPAY_PUBLIC_KEY:env.ALIPAY_PUBLIC_KEY.replaceAll('\n','\\n')},configOnly:true})).ok,true);for(const patch of [{ALIPAY_PRIVATE_KEY:ec.privateKey.export({format:'pem',type:'pkcs8'})},{ALIPAY_PRO_MONTHLY_AMOUNT:'0.00'},{ALIPAY_PRO_MONTHLY_AMOUNT:'129.999'},{ALIPAY_SANDBOX:'true'}])assert.equal((await runPreflight({env:{...env,...patch},configOnly:true})).ok,false);});
test('storage write/fsync/read-back probe is cleaned up and unusable paths fail without a CLI call',async()=>{const good=await runPreflight({env:base,skipCli:true,execute:quiet});assert.equal(good.ok,true);assert.deepEqual(fs.readdirSync(base.GAMESTUDIO_DATA_DIR),[]);const bad=path.join(directory,'not-a-directory');fs.writeFileSync(bad,'fixture');const r=await runPreflight({env:{...base,GAMESTUDIO_DATA_DIR:bad},skipCli:true,execute:quiet});assert.equal(r.ok,false);assert.ok(r.errors.some(x=>x.includes('volume is not writable')));});
test('CLI checks validate exact version and owner-only cache while never printing its returned credential text',async()=>{const authDir=path.join(directory,'auth');fs.mkdirSync(authDir,{mode:0o700});const file=path.join(authDir,'auth.json');fs.writeFileSync(file,'{"fixture":true}',{mode:0o600});const execute=(bin,args)=>args.includes('--version')?'codex-cli 0.160.0':'Logged in using an API key - sk-fixture-hidden';let r=await runPreflight({env:base,authDir,execute});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.ok(!JSON.stringify(r).includes('sk-fixture-hidden'));r=await runPreflight({env:base,authDir,execute:(bin,args)=>args.includes('--version')?'codex-cli 0.150.0':execute(bin,args)});assert.equal(r.ok,false);fs.chmodSync(file,0o644);assert.equal((await runPreflight({env:base,authDir,execute})).ok,false);fs.chmodSync(file,0o600);});
test('model probe is opt-in, fixes exact model/tools/sandbox, and cleans every fixture output without a network call',async()=>{const authDir=path.join(directory,'auth');const calls=[];const execute=(bin,args,opt)=>{calls.push(args);if(args.includes('--version'))return'codex-cli 0.160.0';if(args.includes('status'))return'Logged in using ChatGPT';assert.equal(args[args.indexOf('-m')+1],'gpt-6.1-sol');assert.equal(args[args.indexOf('-s')+1],'read-only');for(const disabled of ['shell_tool','multi_agent','apps'])assert.ok(args.includes(disabled));fs.writeFileSync(args[args.indexOf('--output-last-message')+1],'{"ok":true}');return'';};assert.equal((await runPreflight({env:base,configOnly:true,probeModel:true,execute})).ok,false);assert.equal(calls.length,0);const r=await runPreflight({env:base,authDir,probeModel:true,execute});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(calls.filter(c=>c[0]==='exec').length,1);assert.deepEqual(fs.readdirSync(base.GAMESTUDIO_DATA_DIR),[]);});
process.on('exit',()=>fs.rmSync(directory,{recursive:true,force:true}));
